spring.application.name=auth-service

server.port=8081

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

security.jwt.access-token-expiration-ms=3600000     
security.jwt.refresh-token-expiration-ms=604800000    

