server.port=8081

# DB host inside Docker network
spring.datasource.url=jdbc:mysql://mysql:3306/keep-auth-db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# This will be overridden by SECURITY_JWT_SECRET env variable in docker-compose
security.jwt.secret=default-docker-secret
