spring.application.name=reminder-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/keep-reminder-db
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

security.jwt.secret=auydwfgq8ogr3f8oq3adjiwaiupwclbdwucidiehwu
security.jwt.access-token-expiration-ms=3600000
security.jwt.refresh-token-expiration-ms=604800000

management.endpoints.web.exposure.include=health,info

reminder.scheduler.fixed-delay-ms=60000


# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration