server.port=8082

# DB host is the mysql container name on the docker network
spring.datasource.url=jdbc:mysql://mysql:3306/keep-notes-db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Will be overridden by env in docker-compose
security.jwt.secret=default-docker-secret
