spring.application.name=notes-service

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/keep-notes-db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Same JWT secret as auth-service (for validating tokens)
security.jwt.secret=auydwfgq8ogr3f8oq3adjiwaiupwclbdwucidiehwu
