spring.application.name=search-service
server.port=8086

notes.service.base-url=http://localhost:8082

spring.main.web-application-type=servlet

spring.cache.type=simple

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
